version: '3'

services:

    php:
        container_name: custom
        image: marcelofabianov/php-8.1-fpm-dbs
        restart: always
        working_dir: /var/www/html
        environment:
            TZ: '${TZ:-}'
        volumes:
            - .:/var/www/html
        ports:
            - "9902:9000"
        networks:
            - custom_network
        depends_on:
            - http

    http:
        container_name: custom_http
        image: nginx:latest
        restart: always
        environment:
            TZ: '${TZ:-}'
        ports:
            - "8001:80"
            - "331:443"
        volumes:
            - ./public:/var/www/html/public
            - ./.docker/local/http/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/local/http/logs:/var/log/nginx
        networks:
            - custom_network

networks:
    custom_network:
        driver: bridge
